### ISSUE TITLE
ICP Registration with pycc and cccorelib

### ISSUE THREAD

**Issue by accurate-aayush** [tmontaigu/CloudCompare-PythonRuntime#103]
How would I use ICP Registration with pycc and cccorelib?

def main():
    entities = CC.getSelectedEntities()
    print(f"Selected entities: {entities}")
    
    if not entities:
        raise RuntimeError("No entities selected")
    
    

  
 
    model_cloud = entities[1]  # Assuming the second entity is the model cloud
    data_cloud = entities[0]   # Assuming the first entity is the data cloud

    #model_mesh = cccorelib.GenericIndexedMesh(model_cloud)
    #data_cloud = cccorelib.GenericIndexedCloudPersist(data_cloud)

    params = cccorelib.ICPRegistrationTools.Parameters()
    total_trans = cccorelib.PointProjectionTools.Transformation()
    final_rms = 0.0  # Assuming this is the correct value for final RMS
    final_point_count = 50000  
    progress_cb = None  # Assuming this is the correct type

    rm = cccorelib.ICPRegistrationTools.Register(
        model_cloud,  # Pass the model cloud as the first argument
        data_cloud, # Pass the data cloud as the second argument
        params,
        total_trans,
        final_rms,
        final_point_count,
        progress_cb
    )

I'm getting the following error "[11:21:52] TypeError: Register(): incompatible function arguments. The following argument types are supported:

    1. (modelCloud: cccorelib.GenericIndexedCloudPersist, modelMesh: cccorelib.GenericIndexedMesh, dataCloud: cccorelib.GenericIndexedCloudPersist, params: cccorelib.ICPRegistrationTools.Parameters, totalTrans: cccorelib.PointProjectionTools.Transformation, finalRMS: float, finalPointCount: int, progressCb: cccorelib.GenericProgressCallback = None) -> cccorelib.ICPRegistrationTools.RESULT_TYPE

Invoked with: <ccPointCloud('Mesh.sampled.registered.registered', 999996 points)>, <pycc.ccMesh object at 0x7f124f96b4f0>, <cccorelib.ICPRegistrationTools.Parameters object at 0x7f124f96b5f0>, <cccorelib.PointProjectionTools.Transformation object at 0x7f124f96b630>, 0.0, 0, None

"

**Comment by tmontaigu** [comment]
It would be smart to post the code you used, I'm not a magician and I can't guess it

**Comment by tmontaigu** [comment]
I think you are mising an argument

Based on https://github.com/CloudCompare/CCCoreLib/blob/cac3533c6b9b773d33122a393533e2a328241d5b/include/RegistrationTools.h#L223

If you wan to have a mesh as the model you need to call `.Register(None, modelMesh, ...)` if you want to use a point cloud as the model `.Register(pcModel, None, ...)`

**Comment by accurate-aayush** [comment]
Thanks

**Comment by accurate-aayush** [comment]
> I think you are mising an argument
> 
> Based on https://github.com/CloudCompare/CCCoreLib/blob/cac3533c6b9b773d33122a393533e2a328241d5b/include/RegistrationTools.h#L223
> 
> If you wan to have a mesh as the model you need to call `.Register(None, modelMesh, ...)` if you want to use a point cloud as the model `.Register(pcModel, None, ...)`

IF modelMesh is set to None, CloudCompare crashes, ideally i want to compare modelMesh to dataCloud, Thanks

**Comment by tmontaigu** [comment]
I tried to but it does not crash

Is it really a crash (CloudCompare abruptly closes) or does the window becomes unresponsive ?

If its the window that becomes unresponsive then pass a non None progress callback like so
``` Python
progress = pycc.ccProgressDialog()
progress.setMethodTitle("Registering")
progress.start()
```


If it's a real crash, then I would need the full script and possibly the data
