### ISSUE TITLE
point clouds in folders

### ISSUE THREAD

**Issue by Ellana17** [tmontaigu/CloudCompare-PythonRuntime#110]
Bonjour,

Avec mon script python, je découpe plusieurs fichiers ce qui me donne parfois une dizaine de nuages de points. Je voudrai que ces nuages de points s'affichent dans des dossiers comme lorsqu'on importe les fichiers directement depuis l'interface CloudCompare, comment faire avec python ?
![image](https://github.com/tmontaigu/CloudCompare-PythonRuntime/assets/46356920/b9abea9f-55c7-4b1e-89a0-3ae682ff8980)
Désiré : 
![image](https://github.com/tmontaigu/CloudCompare-PythonRuntime/assets/46356920/cd2c67f2-6dbc-456f-bfa8-4bfa3b8a50ac)

Code utilisé:
```
def cloud(l1,l2,T,en_tete,idx_sf,output_file_T):
    point_cloud=pycc.ccPointCloud(T[l1:l2,1].astype(pycc.PointCoordinateType), T[l1:l2,2].astype(pycc.PointCoordinateType), T[l1:l2,3].astype(pycc.PointCoordinateType))    
    for l in range(len(idx_sf)):
        idx = point_cloud.addScalarField(en_tete[idx_sf[l]], T[l1:l2,idx_sf[l]]) # utile pour le minmax
        point_cloud.getScalarField(point_cloud.getScalarFieldIndexByName(en_tete[idx_sf[l]])).computeMinAndMax()
    point_cloud.setName(output_file_T) 
    CC.addToDB(point_cloud)

```
Merci d'avance

**Comment by tmontaigu** [comment]
A cause d'un bug ce n'est pas encore possible de faire ca, je vais tenter de la corriger

**Comment by Ellana17** [comment]
Merci beaucoup ce serait super
