### ISSUE TITLE
Build PythonRuntime as Plugin

### ISSUE THREAD

**Issue by zhuimeng00** [tmontaigu/CloudCompare-PythonRuntime#111]
In Windows environment, when following the file operation to step 5 Generate the cmake config, the following error appears:
<img width="1277" alt="error" src="https://github.com/tmontaigu/CloudCompare-PythonRuntime/assets/113812029/121efd41-4639-4460-a28d-bbeacc04e29c">
When I follow method 2 to perform this step, the same error message appears. What confuses me is that when using Cmake to generate C++ files, there will be no such error message.
I hope to get your generous answer.

**Comment by tmontaigu** [comment]
Source is cloudcompare sources not the plugin sources

**Comment by zhuimeng00** [comment]
I got it. Thanks for your reply.
