### ISSUE TITLE
define a color scale 

### ISSUE THREAD

**Issue by Ellana17** [tmontaigu/CloudCompare-PythonRuntime#113]
Bonjour,

j'utilise cloudcompare pour afficher plusieurs nuages de points avec la vibration comme valeurs pour l'échelle de couleur.
Actuellement j'utilise ce code :

```
def cloud_slog(ordered_T,ordered_header,file_name_slog_output,xi,yi,zi,SLOG_color_scale_index):
    point_cloud=pycc.ccPointCloud(ordered_T[:,int(xi)].astype(pycc.PointCoordinateType), ordered_T[:,int(yi)].astype(pycc.PointCoordinateType), ordered_T[:,int(zi)].astype(pycc.PointCoordinateType))
    print(ordered_header)
    idx_sf= [i for i in range(0,len(ordered_header)-1)]  # Future liste des indices des "scalar fiels"
    idx_sf.remove(int(xi))
    idx_sf.remove(int(yi))
    idx_sf.remove(int(zi))
    print(idx_sf)

    for l in range(len(idx_sf)):
        idx=point_cloud.addScalarField(ordered_header[idx_sf[l]], ordered_T[:,idx_sf[l]])
        point_cloud.getScalarField(point_cloud.getScalarFieldIndexByName(ordered_header[idx_sf[l]])).computeMinAndMax()
        if idx_sf[l]==SLOG_color_scale_index:
            point_cloud.setCurrentDisplayedScalarField(idx)
            point_cloud.showSFColorsScale(True)
            point_cloud.showSF(True)

    point_cloud.setName(file_name_slog_output) 
    CC.addToDB(point_cloud)
```

A la place de '''.computeMinAndMax()''' j'aimerai définir moi-même le min et max de l'échelle de couleurs, pour avoir une même échelle pour tous les nuages de points.
Que dois-je changer ?

Merci d'avance

**Comment by tmontaigu** [comment]
Il doit falloir calculer le min et max global sur l'ensemble des champs
et ensuite appeler sur chaque scalar field `setMinDisplayed(min)` et `setMaxDisplayed(max)`

**Comment by Ellana17** [comment]
'''
    for l in range(len(idx_sf)):
        idx=point_cloud.addScalarField(ordered_header[idx_sf[l]], ordered_T[:,idx_sf[l]])
        scalar_field=point_cloud.getScalarField(point_cloud.getScalarFieldIndexByName(ordered_header[idx_sf[l]]))#
        scalar_field.setMinDisplayed(2)
        scalar_field.setMaxDisplayed(50)
        if idx_sf[l]==SLOG_color_scale_index:
            point_cloud.setCurrentDisplayedScalarField(idx)
            point_cloud.showSFColorsScale(True)
            point_cloud.showSF(True)
    point_cloud.setName(file_name_slog_output) 
    CC.addToDB(point_cloud)
'''
me donne : 
![image](https://github.com/user-attachments/assets/6af4c68d-3983-4dd2-8028-e05679f25ccb)
L'échelle de couleur est à 0 pour tous les scalar field. Quel peut être le problème ?

**Comment by tmontaigu** [comment]
Enfaite, en regardant le code de CoudCompare, setMaxDisplayed/setMinDisplayed ne fonctionnera pas car les valeur donne a ces fonctions sont troque pour rester dans le min/max du field

Du coup en apparence ça n'a pas l'air d’être possible, peut etre sur qu'en posant sur le repo CloudCompare il pourrait confirmer si c'est possible ou non
