### ISSUE TITLE
add vectors x y z

### ISSUE THREAD

**Issue by Ellana17** [tmontaigu/CloudCompare-PythonRuntime#115]
Bonjour,

Je souhaiterai créer en python un petit programme qui affiche le point (0,0,0) ainsi que les vecteurs x,y et z partant de ce point. Dans CloudCompare, lors de l'import d'un fichier, Nx, Ny et Nz sont des "types de données" qui peuvent être choisit. Comment les choisir en python ?

Merci d'avance

**Comment by tmontaigu** [comment]
Lors de l'import d'un fichier (quel format) il est possible de specifier un point d'origine et les vecteur de bases ?

**Comment by Ellana17** [comment]
J'utilise cloudcompare pour afficher plusieurs nuages de points avec la vibration comme valeurs pour l'échelle de couleur. 
Comme il n'est pas possible de définir une échelle globale (define a color scale #113 ) j'ai ajouté dans mon script python un calcul des valeurs min/max "générales" et j'ai ajouté à la fin de chaque fichier 2 lignes avec le min et le max aux coordonnées (0,0,0). Il y a donc p=2x"nb de nuages" points (0,0,0) qui se retrouvent "tout seuls"  et j'aimerai rajouter des vecteurs X,Y,Z sur ces points pour qu'on comprennent qu'il ne s'agit pas d'usinage mais de l'origine de la pièce (les coordonnées des nuages de points étant selon la "position origine pièce").

La solution serait donc d'importer (ou de créer directement en python) le fichier csv suivant :
![image](https://github.com/user-attachments/assets/8b027ea0-b661-4c59-91a5-ae4b1aeb5ae3)

Mais comment faire pour que lors de l'import/ l'utilisation des données Nx,Ny et Nz soient considérés comme des vecteurs : 
![image](https://github.com/user-attachments/assets/6dbc2a12-e49b-4b34-9dcc-54f89b7df2bf)

et si possible que la case "Draw" soit cochée automatiquement
![image](https://github.com/user-attachments/assets/b7fdeb0a-58a9-432d-9792-ae8a8b2e9a0d)

Importé "à la main", le fichier donne ça (avec une modification de "length"): 
![image](https://github.com/user-attachments/assets/3eff4dcc-74ec-4e31-90ac-3d2ad86be7dd)

**Comment by tmontaigu** [comment]
```Python
import numpy as np
import pycc

cc = pycc.GetInstance()

x = np.array([0, 0, 0])
y = np.array([0, 0, 0])
z = np.array([0, 0, 0])

normals = np.array([[0, 0, 1], [0, 1, 0], [1, 0, 0]])
print(normals[:, 0], normals[:, 1], normals[:, 2])

pc = pycc.ccPointCloud(x, y, z)
pc.reserveTheNormsTable()
pc.addNormals(normals[:, 0], normals[:, 1], normals[:, 2])
pc.setName("origin")
pc.showNormalsAsLines(True)
cc.addToDB(pc)
cc.updateUI()
```

Ce bout de code va creer un point cloud qui va creer un point a l'origine avec les normals comme vecteurs de base, avec la case draw coche. Mais le normales ne sont visible que l'lorsque l'on bouge la vue 🤔 

Est ce que ca s'approche de ce qui est voulu ?

**Comment by Ellana17** [comment]
Désolé de répondre si tard, j'étais en vacances.

**Comment by tmontaigu** [comment]
Le nouvelle version comprise dans l'installeur contient la fonction pour avoir la case `draw` choché en faisant `pc.showNormalsAsLines(True)`

Par contre je ne sais pas comment augmenter la talle des vecteurs
