### ISSUE TITLE
polyline how to setColor

### ISSUE THREAD

**Issue by eglrp** [tmontaigu/CloudCompare-PythonRuntime#117]
I want to draw polyline with color,but how to setColor
```python
import pycc
import numpy as np

CC = pycc.GetInstance()
VERTICES = np.array([
    [-0.5, -0.5, 0],
    [1, 1, 0],
[2, 2, 0]
])
vertices = pycc.ccPointCloud(VERTICES[:, 0], VERTICES[:, 1], VERTICES[:, 2])
polyline = pycc.ccPolyline(vertices)
polyline.setColor()
polyline.setClosed(False)
# This is important, otherwise the polyline would have a size of 0
polyline.addPointIndex(0, 3)
CC.addToDB(polyline)
CC.updateUI()
```
![image](https://github.com/user-attachments/assets/2a3578ab-2111-4ac4-b530-707649772104)

**Comment by tmontaigu** [comment]
the setColor is not completely functional yet, it will be when I re generate the installer

**Comment by tmontaigu** [comment]
The new installer is up and contains the appropriate things

`polyline.setColor(pycc.Rgb(255, 0, 0)) # set the color to red`

**Comment by eglrp** [comment]
good

**Comment by Mirandatz** [comment]
Hello @tmontaigu I am still having this issue with cloud compare 2.13.2 (flatpak).
Is there anything I can do to get the pycc.Rgb?

**Comment by tmontaigu** [comment]
Hum It seems the flatpak contains a version of the runtime that is a bit too old and does not have this

I'll try to propose an update to the maintainers

**Comment by tmontaigu** [comment]
The new beta has the functionality to install it you need to have the flathub beta repo
```
flatpak remote-add --if-not-exists flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo
```

Then you can install it via 
```
flatpak install flathub-beta org.cloudcompare.CloudCompare
```

or use your distro's GUI (like KDE discover) by selecting Flathub beta as the flatpak source
