### ISSUE TITLE
How to use the function ccGenericGLDisplay. DisplayText

### ISSUE THREAD

**Issue by eglrp** [tmontaigu/CloudCompare-PythonRuntime#118]
I want to display file characters in cc
![image](https://github.com/user-attachments/assets/36246d5c-93f0-4225-adff-d3eecf122592)

**Comment by tmontaigu** [comment]
I tried to look into it, first thats not how you get a ccGenericGLDisplay you need to have an entity like a point cloud cloud
and do `point_cloud.getDisplay()`

However when reading the documentation of `displayText` it seems like its not means to be used at a specific time at so it likely won't work, and I don't know the proper way to be able to display some generic text
