### ISSUE TITLE
Coordinate request 2.14.alpha vs 2.13.2

### ISSUE THREAD

**Issue by mariolino007** [tmontaigu/CloudCompare-PythonRuntime#124]
hello Thomas,

please note that with python inside CC 2.13.2 the request for point coordinates via the following code works, whereas in version CC 2.14.alpha for all coordinates only one value is always returned (perhaps the first....)
All the codes I have written now do not work inside CC 2.14.alpha ..... is it possible to do something ?

thanks
Mario

```
import pycc
import numpy as np
cc = pycc.GetInstance()
entities = cc.getSelectedEntities()
if len(entities) != 1:
    print("\nselect point cloud")
else:
    entity = entities[0]
    if isinstance(entity, pycc.ccPointCloud):
        cloud_coordinates = np.array(entity.points())
        print("\ncoords:")
        for point in cloud_coordinates:
            print(f"({point[0]}, {point[1]}, {point[2]})")
    else:
        print("\nEntity is not a point cloud")

```

**Comment by tmontaigu** [comment]
That's strange I will investigate

**Comment by tmontaigu** [comment]
Hum, its strange, I tried with a local version and the one on CloudCompare website and it works as expected

**Comment by mariolino007** [comment]
verified with 2.14 built 29/9/2024
error corrected, code works !!
