### ISSUE TITLE
How to get the TLS/GLB Position/Orientation matrix 

### ISSUE THREAD

**Issue by LoicBrouet** [tmontaigu/CloudCompare-PythonRuntime#42]
Hello,

I working with laser scans from a fixed laser scanner, and there is a small offset in the scan orientation (different for each one). I need to correct it to compare the scans between each other. I can do it manually with CloudCompare by extracting the TLS/GLB Position/Orientation matrix, and by applying a transformation (this second step is automated with the command line). However I have a lot of scans (6000) and I would like to automate the extraction of the TLS/GLB Position/Orientation matrix (this matrix is indicated in the attached picture). 

I'm trying to use your plugin for that (built with the windows installer). The function "getAbsoluteTransformation" of the class pycc.ccSensor seems appropriated for that, although there is no precise description, however I cannot find the right synthaxe to make it works. I wrote the following code that I open and run with the code editor window in CloudCompare.  

Is the function "getAbsoluteTransformation" return the TLS/GLB Position/Orientation matrix? If yes, would you have any suggestion for the synthaxe? If no, is there a function that could do this?

Thank you for your help
Loïc

```
import pycc

CC = pycc.GetInstance()

params = pycc.FileIOFilter.LoadParameters()
params.parentWidget = CC.getMainWindow()

path = r"C:\Users\brouetlo\Desktop\Laser_scanner\fls_scans\Scan_WFJ_2022-05-26_08-31-31.fls\Scan_WFJ_070.fls"

obj = pycc.FileIOFilter.LoadFromFile(path, params)

matrix = pycc.ccSensor.getAbsoluteTransformation
print(matrix)

```

![Screenshot (1)](https://user-images.githubusercontent.com/75834223/190416748-c7d77205-46ee-43fc-9f22-54e316576dba.png)

**Comment by tmontaigu** [comment]
What does this code outputs?

I see you are missing the `()` to call the `getAbsoluteTransformation`

**Comment by LoicBrouet** [comment]
The output is `<instancemethod getAbsoluteTransformation at 0x000001766BDC3C40>`, and the variable type of `matrix` is `<class 'instancemethod'>`. 

I tried to add the `()` but I get the error message : 
```
TypeError: getAbsoluteTransformation(): incompatible function arguments. The following argument types are supported:
    1. (self: pycc.ccSensor, trans: ccIndexedTransformation, index: float) -> bool

Invoked with: 

At:
  <string>(13): <module>
```

**Comment by LoicBrouet** [comment]
Would you have any suggestion or more explicit documentation about these functions and synthax? 
Thank you, Loïc

**Comment by tmontaigu** [comment]
I'll answer you before the end of the week, I haven't had the time to look into it until now

**Comment by LoicBrouet** [comment]
Alright thank you

**Comment by tmontaigu** [comment]
So if download the latest installer you should be able to access the transformation

here is a sample script

```Python
import pycc

CC = pycc.GetInstance()

params = pycc.FileIOFilter.LoadParameters()
params.parentWidget = CC.getMainWindow()


def find_child_by_name(parent, child_name):
    for i in range(parent.getChildrenNumber()):
        child = parent.getChild(i)
        if child.getName() == child_name:
            return child
    return None           

def main():
    obj = CC.getSelectedEntities()[0]
    print("Selected object name: ", obj.getName())
    
    station_child = find_child_by_name(obj, "Station 018")
    if station_child is None:
        raise RuntimeError("Station 018 not found")
    
    gbl_sensor = find_child_by_name(station_child, "TLS/GBL")
    if gbl_sensor is None:
        raise RuntimeError("no gbl sensor found")

    transform = pycc.ccIndexedTransformation()
    i = gbl_sensor.getActiveIndex()
    succeeded = gbl_sensor.getAbsoluteTransformation(transform, i)
    if not succeeded:
        raise RuntimeError("Failed to get absolute transformation")

    print(transform.asArray())

main()
```

**Comment by LoicBrouet** [comment]
Thank you very much, it works ! 

I would like to load automatically the scans so that the process works only by running the code, however when I load a scan a window appears for colors loading (see picture attached) and I need to click on yes or no to continue the process. Is there a possibility to ignore this window, such as the silent mode (-SILENT) with the CC command line?

![Screenshot (3)](https://user-images.githubusercontent.com/75834223/194041253-e83db0e3-10ce-459d-9cba-ad61721486e0.png)


here is your sample script adapted 

```
import pycc
import numpy as np

CC = pycc.GetInstance()

params = pycc.FileIOFilter.LoadParameters()
params.parentWidget = CC.getMainWindow()

def find_child_by_name(parent, child_name):
    for i in range(parent.getChildrenNumber()):
        child = parent.getChild(i)
        if child.getName() == child_name:
            return child
    return None           

def main():

    path = r"C:\Users\...\Scan_WFJ_2022-05-26_08-31-31.fls\Scan_WFJ_070.fls"
    
    obj = pycc.FileIOFilter.LoadFromFile(path, params)
    print("Selected object name: ", obj.getName())
    
    station_child = find_child_by_name(obj, "Scan_WFJ_2022-05-26_08-31-31")
    if station_child is None:
        raise RuntimeError("Station child not found")
    
    gbl_sensor = find_child_by_name(station_child, "TLS/GBL")
    if gbl_sensor is None:
        raise RuntimeError("no gbl sensor found")

    transform = pycc.ccIndexedTransformation()
    i = gbl_sensor.getActiveIndex()
    succeeded = gbl_sensor.getAbsoluteTransformation(transform, i)
    if not succeeded:
        raise RuntimeError("Failed to get absolute transformation")

    print(transform.asArray())
    np.savetxt('C:/Users/.../matrix.txt',transform.asArray())

main()
```

**Comment by tmontaigu** [comment]
you can try `params.alwaysDisplayLoadDialog=False`, and hope that the file io filter respects it

**Comment by LoicBrouet** [comment]
It works, thanks a lot for your help!
