### ISSUE TITLE
get normals and color from pointcloud

### ISSUE THREAD

**Issue by mariolino007** [tmontaigu/CloudCompare-PythonRuntime#89]
hello,
is there a function to import normal and RGB colour values from a point cloud 
thank you very much !!

**Comment by tmontaigu** [comment]
Hello,

To get the colors value you have the `colors` method that returns a numpy array
```
point_cloud.colors()
```


For normals its not yet possible to extract them,

It should however be possible to add the function `exportNormalToSF`, so that normals appears as scalar field which you can then retrieve

**Comment by tmontaigu** [comment]
Closing as its now possible to get normals and colors (and change them)
