### ISSUE TITLE
Get triangulation from mesh

### ISSUE THREAD

**Issue by mariolino007** [tmontaigu/CloudCompare-PythonRuntime#94]
hello,
I wanted to perform some operations on meshes. I was able to create the instance for a mesh, I was able to perform operations on the coordinates associated with the mesh cloud, but I can't request the triangulation of the mesh and recreate it in the new one.

new_mesh = pycc.ccMesh([], [], [])
new_mesh.addPoints(transformed_coordinates[0], transformed_coordinates[1], transformed_coordinates[2])
new_mesh.addTriangleIndex(triangle[0], triangle[1], triangle[2])
new_mesh.setName("Transformed Mesh")
cc.addToDB(new_mesh, autoExpandDBTree=False)
cc.updateUI()

**Comment by tmontaigu** [comment]
Hello, I'm not sure I understand what you want

**Comment by mariolino007** [comment]
Sorry for the delay in writing to you, for the meshes that already exist in CC, I was able to make the vertex request (which in CC is the point cloud associated with the mesh), then I think by giving an internal numbering to these vertices, there is a property in CC that indicates for each triangle a triplet of vertices in the cloud that identifies each individual triangle in the mesh, I think in essence it's like the PLY format of meshes.
https://paulbourke.net/dataformats/ply/

function like get.triangole.triplets ?

Many Thanks

PS for meshes I couldn't find any code demos in 
https://tmontaigu.github.io/CloudCompare-PythonRuntime/examples

**Comment by tmontaigu** [comment]
Ok I understand, I'll try to see If I can make an example and add what is missing

**Comment by tmontaigu** [comment]
This is actually already possible
```Python
import pycc
import cccorelib


CC = pycc.GetInstance()

mesh = CC.getSelectedEntities()[0]
vertices = mesh.getAssociatedCloud()

num_triangles = mesh.size()

print(f"The mesh has {num_triangles} triangles")
print(f"The cloud has {vertices.size()} points") 

# Way 1
x, y, z = cccorelib.CCVector3(), cccorelib.CCVector3() ,cccorelib.CCVector3()
vert_indices = mesh.getTriangleVertIndexes(0)
vertices.getPoint(vert_indices.i1, x)
vertices.getPoint(vert_indices.i2, y)
vertices.getPoint(vert_indices.i3, z)
print(f"For triangle 0: \n"
      f"indices are {vert_indices.i1} {vert_indices.i2} {vert_indices.i3}\n"
      f"points are {x} {y} {z}"
)

# Way 2

vert_indices = mesh.getTriangleVertIndexes(0)
points = [cccorelib.CCVector3(), cccorelib.CCVector3() ,cccorelib.CCVector3()]
for i, p in enumerate(points):
    vertices.getPoint(i, p)
print(f"For triangle 0: \n"
      f"indices are {vert_indices.i1} {vert_indices.i2} {vert_indices.i3}\n"
      f"points are {x} {y} {z}"
)


# Way 3
x, y, z = cccorelib.CCVector3(), cccorelib.CCVector3() ,cccorelib.CCVector3()
mesh.getTriangleVertices(0, x, y ,z)
print(f"For triangle 0: \n"
      f"indices are {vert_indices.i1} {vert_indices.i2} {vert_indices.i3}\n"
      f"points are {x} {y} {z}"
)
```

**Comment by mariolino007** [comment]
many thanks !!!
your toolbox is great and you have programmed it really well, my programming level is quite basic I understand well are with examples. 
I ask too much if you could make also more examples also about meshes ?
- Create a mesh from scratch (for example 100 random points cloud associated points and 100 random triangles connecting each three random vertices of the cloud) ? 
- Modify existing selected mesh by randomly deleting 50% of the triangles or adding 50% random new trinagles ?
Thank you very much for your patience
Mariolino

**Comment by tmontaigu** [comment]
If you install  the latest version from the installer you will be able to run the example at https://tmontaigu.github.io/CloudCompare-PythonRuntime/examples.html#using-ccmesh

**Comment by mariolino007** [comment]
a perfect job !!! 
congratulations the command for mesh works great !!!

One strange thing is that by installing CC(clean no python) + CloudCompare-PythonRuntime-Setup-English-Python9-Venv, the ccMesh demo works perfectly, with "import scipy" (preloaded in your distribution) it goes in error, installing for example "solid" then when I do "import solid" also in error, instead "import np" works correctly

many thanks

Do you have a web page / instragram / linkedin ?


Translated with DeepL.com (free version)

**Comment by tmontaigu** [comment]
> , with "import scipy" (preloaded in your distribution) it goes in error, instead "import 

Where is that 'import scipy' I don't see it in the code ?

I do have [linkedin](https://www.linkedin.com/in/thomas-montaigu-559ba8155/)

**Comment by mariolino007** [comment]
inside ccmesh is not used "import scipy", but wth a new program with "import scipy" it goes in error.....

**Comment by tmontaigu** [comment]
Ah that's because my installer only comes with numpy as its mandatory for some cccorelib/pycc functionalities

The ones from cloudcompare website probably comes with scipy because de 3DFin plugin requires it
