### ISSUE TITLE
Point cloud visualization problem

### ISSUE THREAD

**Issue by polzaco** [tmontaigu/CloudCompare-PythonRuntime#98]
Hi everyone!

We are using pycc for point clouds segmentation. When we store the point cloud in the database of cc with the following code, the points results are wrong :

# CREATE THE RESULTING POINT CLOUD 
            # Load the predictions
            pcd_prediction = pd.read_csv(os.path.join(self.output_directory,'predictions.txt'), sep=',')  # Use sep='\t' for tab-separated files       

            # Select only the 'Predictions' column
            pc_results_prediction = pycc.ccPointCloud(pcd_prediction['X'], pcd_prediction['Y'], pcd_prediction['Z'])
            pc_results_prediction.setName("Results_from_segmentation")
            idx = pc_results_prediction.addScalarField("Labels",pcd_prediction['Predictions']) 
            
            # STORE IN THE DATABASE OF CLOUDCOMPARE
            CC = pycc.GetInstance()
            CC.addToDB(pc_results_prediction)
            CC.updateUI() 

Firstly, I would prefer open it with the Scalar Field view at the beginning, because it appears with None. (first picture)
![Captura de pantalla 2024-03-08 160300](https://github.com/tmontaigu/CloudCompare-PythonRuntime/assets/107433987/a2f3d024-e8c4-4609-b4e5-be1244fdbd5a)

Then, after the scalar field activation , the point cloud only open the first class color, the rest dont open. (second picture)
![Captura de pantalla 2024-03-08 160321](https://github.com/tmontaigu/CloudCompare-PythonRuntime/assets/107433987/22cddd48-0264-436f-88c1-31d9de0d0091)

It should appear at the first time like that. I did with "Split cloud (integer values)" tool and then merging all of them (thrid picture)
![Captura de pantalla 2024-03-08 160508](https://github.com/tmontaigu/CloudCompare-PythonRuntime/assets/107433987/5efec15e-cdf1-4bbe-a1d8-594387cb8110)

Is possible to do that?
Thanks in advance.

**Comment by tmontaigu** [comment]
To show a scalar field by default you have to call `point_cloud.setCurrentDisplayedScalarField(idx)`

And to CC to show nice colors you have to call `computeMinAndMax` on the scalar field
`point_cloud.getScalarField(point_cloud.getScalarFieldIndexByName("classification")).computeMinAndMax()`
